var resizeId,iniScrWidth=screen.width;function resizeRefresh(){clearTimeout(resizeId);if(iniScrWidth!==screen.width)resizeId=setTimeout(doneResizing,500)}function doneResizing(){location.reload();console.log("resized")}d3.select(window).on("resize",resizeRefresh);
function chordMpr(n){var m={},c={},o=0,k=[],j,f;m.setFilter=function(a){j=a;return this};m.setAccessor=function(a){f=a;return this};m.getMatrix=function(){k=[];_.each(c,function(a){k[a.id]||(k[a.id]=[]);_.each(c,function(e){var h=_.filter(n,function(g){return j(g,a,e)});k[a.id][e.id]=f(h,a,e)})});return k};m.getMap=function(){return c};m.printMatrix=function(){_.each(k,function(a){console.log(a)})};m.addToMap=function(a,e){c[a]||(c[a]={name:a,id:o++,data:e})};m.addValuesToMap=function(a,e){var h=
_.uniq(_.pluck(n,a));_.map(h,function(g){c[g]||(c[g]={name:g,id:o++,data:e})});return this};return m}
function chordRdr(n,m){return function(c){var o,k,j,f,a={};if(c.source){o=c.source.index;k=c.target.index;j=_.where(m,{id:o});f=_.where(m,{id:k});a.sname=j[0].name;a.sdata=c.source.value;a.svalue=+c.source.value;a.stotal=_.reduce(n[o],function(e,h){return e+h},0);a.tname=f[0].name;a.tdata=c.target.value;a.tvalue=+c.target.value;a.ttotal=_.reduce(n[k],function(e,h){return e+h},0)}else{o=_.where(m,{id:c.index});a.gname=o[0].name;a.gdata=o[0].data;a.gvalue=c.value}a.mtotal=_.reduce(n,function(e,h){return e+
_.reduce(h,function(g,b){return g+b},0)},0);return a}}
function drawBarPrisoners(){function n(j){j.percentage=+j.percentage;return j}function m(){d3.select(this).select("rect").transition().duration(300).ease("bounce").style("fill","#ED7149");d3.select(this).select(".barRectTitle").transition().duration(150).ease("cubic").style("opacity","0").style("font-weight","700").transition().duration(150).style("opacity","1").text(function(j){return j.percentage+" %"})}function c(){d3.select(this).select("rect").transition().duration(300).ease("exp").style("fill","#ED9F85");
d3.select(this).select(".barRectTitle").transition().duration(150).style("opacity","0").transition().style("font-weight","500").duration(150).style("opacity","1").text(function(j){return j.country})}var o=parseInt(d3.select("#barPrisoners").style("width")),k;d3.select("#barPrisoners").append("svg").attr("id","prisonersContainer").style("display","block").style("margin","auto");(function(){var j=d3.scale.linear().range([0,o]),f=d3.svg.axis().scale(j).orient("bottom").ticks(5),a=d3.select("#prisonersContainer").attr("width",
o);a.append("g").attr("id","prisonersGrid");a.append("g").attr("id","prisonersBars");d3.csv("data/bar-percentage.csv",n,function(e,h){j.domain([0,d3.max(h,function(b){return b.percentage})]);k=(28*h.length+20)*1;a.attr("height",k);var g=a.select("#prisonersBars").selectAll("g").data(h).enter().append("g").attr("class","bars").attr("transform",function(b,i){return"translate(0,"+i*28+")"});g.append("rect").attr("class","barRect").style("fill","#ED9F85").attr("width",function(b){return j(b.percentage)}).attr("height",
20);g.append("text").attr("class","barRectTitle selectDisallow").attr("x",5).attr("y",10).attr("dy",".35em").style("fill","#000000").style("font-size","0.7em").text(function(b){return b.country});a.select("#prisonersGrid").append("g").attr("class","x axis").attr("transform","translate(0,"+(k-20)+")").call(f.tickSize(-k,3).tickPadding(5));a.selectAll(".bars").on("mouseover",m).on("mouseout",c)})})()}
function drawBarIncome(){function n(f){f.income=+f.income;return f}function m(){d3.select(this).select("rect").transition().duration(300).ease("bounce").style("fill","#5bc1ba");d3.select(this).select(".barRectTitle").transition().duration(150).ease("cubic").style("opacity","0").style("font-weight","700").transition().duration(150).style("opacity","1").text(function(f){return f.income+" \u20ac"})}function c(){d3.select(this).select("rect").transition().duration(300).ease("exp").style("fill","#9CD4D1");
d3.select(this).select(".barRectTitle").transition().duration(150).style("opacity","0").transition().style("font-weight","500").duration(150).style("opacity","1").text(function(f){return f.country})}var o=parseInt(d3.select("#barPrisoners").style("width"));d3.select("#barIncome").append("svg").attr("id","salaryContainer").style("display","block").style("margin","auto");var k=d3.scale.linear().range([0,o]),j=d3.svg.axis().scale(k).orient("bottom").ticks(4);(function(){var f=d3.select("#salaryContainer").attr("width",
o);f.append("g").attr("id","salaryGrid");f.append("g").attr("id","salaryBars");d3.csv("data/bar-income.csv",n,function(a,e){k.domain([0,d3.max(e,function(b){return b.income})]);var h=28*e.length+20;f.attr("height",h);var g=f.select("#salaryBars").selectAll("g").data(e).enter().append("g").attr("class","bars").attr("transform",function(b,i){return"translate(0,"+i*28+")"});g.append("rect").attr("class","barRect").style("fill","#9CD4D1").attr("width",function(b){return k(b.income)}).attr("height",20);
g.append("text").attr("class","barRectTitle selectDisallow").attr("x",5).attr("y",10).attr("dy",".35em").style("fill","#000000").style("font-size","0.7em").text(function(b){return b.country});f.select("#salaryGrid").append("g").attr("class","x axis").attr("transform","translate(0,"+(h-20)+")").call(j.tickSize(-h,3).tickPadding(5));f.selectAll(".bars").on("mouseover",m).on("mouseout",c)})})()}
function drawChordDiagram(){var n={top:10,left:25,right:25,bottom:10},m=parseInt(d3.select("#chordDiagram").style("width"));m=m-n.left-n.right;var c=m*0.75;(function(){function o(k,j){function f(d){d3.format(".2%");return"Prisoner Relationship<br/>"+d.sname+" → "+d.tname+" : "+d.svalue+(d.sname===d.tname?"":"<br/>"+d.tname+" → "+d.sname+" : "+d.tvalue)}function a(d){var l=d3.format(".1%"),r=d3.format(",");return d.gname+" has "+r(d.gvalue)+" citizens in EU prisons<br/>This is "+
l(d.gvalue/d.mtotal)+" of the total EU expat prison population."}var e=c/2-100,h=d3.scale.ordinal().domain(d3.range(28)).range(["#a9bccd","#d3b54d","#737fd7","#9dc067","#d78ada","#548d42","#d7609d","#62c78d","#e87579","#55799f","#d04b74","#52aabf","#ce7144","#71a5e2","#ad772e","#9966ac","#85822d","#d0acde","#c1b474","#69cec3","#e3a471","#5b886f","#b85a59","#afb998","#c47495","#98765b","#937c94","#dca8a3"]),g=d3.layout.chord().padding(0.04).sortSubgroups(d3.descending).sortChords(d3.descending),b=
d3.svg.arc().innerRadius(e+10).outerRadius(e+30),i=d3.select("#chordDiagram").append("svg:svg").attr("width",m).attr("height",c).attr("id","chordContainer").style("display","block").style("margin","auto").append("svg:g").attr("id","circle").attr("transform","translate("+m/2+","+c/2+")");i.append("circle").attr("r",e+20);var p=chordRdr(k,j);g.matrix(k);var q=i.selectAll("g.group").data(g.groups()).enter().append("svg:g").attr("class","group").attr("id",function(d){return"ch"+p(d).gname}).on("mouseover",
function(d,l){if(!d3.select("#gActive").empty()&&d3.select(this).attr("id")!=="gActive"){var r=d3.select("#gActive").data()[0].index,t=d3.select("#gActive").text(),s,y=d3.select(this).data()[0].index,z=d3.select(this).text(),w,x=d3.select("#chordContainer").selectAll(".chord").filter(function(u){if(u.source.index===r&&u.target.index===y||u.source.index===y&&u.target.index===r)return u}).data();if(x.length<1)w=s=0;else{s=x[0].source.value;w=x[0].target.value}d3.select("#tooltip").style("opacity",0).style("visibility",
"visible").html(function(){return"Prisoner Relationship<br></1>"+t+" → "+z+": "+s+"<br/>"+z+" → "+t+": "+w}).style("top",function(){return d3.event.pageY+50+"px"}).style("left",function(){return d3.event.pageX-130+"px"})}else d3.select("#tooltip").style("opacity",0).style("visibility","visible").html(a(p(d))).style("top",function(){return d3.event.pageY+50+"px"}).style("left",function(){return d3.event.pageX-130+"px"});d3.select("#tooltip").transition().duration(400).ease("cubic").style("opacity",
1);d3.select(this).select("text").style("font-weight","800");d3.select("#gActive").empty()&&d3.select(this).select("text").style("font-size","0.8em");v.classed("fade",function(u){return u.source.index!=l&&u.target.index!=l});d3.selectAll(".chord").filter(".fade").transition().delay(200).duration(100).style("opacity","0")}).on("mousemove",function(){d3.select("#tooltip").style("left",d3.event.pageX+20+"px").style("top",d3.event.pageY+20+"px")}).on("mouseout",function(){d3.select("#tooltip").style("visibility",
"hidden");if(d3.select(this).attr("id")==="gActive")d3.selectAll(".fade").style("visibility","hidden");else{d3.select(this).select("text").style("font-size","0.6em");d3.selectAll(".fade").transition().delay(100).duration(100).style("opacity",0.8);d3.selectAll("fade").style("visibility","hidden").classed("fade",false);d3.select(this).select("text").style("font-weight","500")}}).on("click",function(){if(d3.select("#gActive").empty()){d3.select(this).attr("id","gActive");d3.select(this).select("text").style("font-size",
"0.8em");d3.select(this).select("path").style("stroke","#424242").style("stroke-width","2")}else if(d3.select(this).attr("id")==="gActive"){d3.select(this).attr("id",null).select("text").style("font-size","0.6em");d3.select(this).select("path").style("stroke","none");d3.selectAll(".fade").style("visibility","visible")}else!d3.select("#gActive").empty()&&d3.select(this).attr("id")!=="gActive"&&d3.select("#gActive").select("text").transition().duration(100).ease("cubic").style("fill","red").transition().duration(100).ease("cubic").style("fill",
"white").transition().duration(100).ease("cubic").style("fill","red").transition().duration(100).ease("cubic").style("fill","white").transition().duration(100).ease("cubic").style("fill","black")});q.append("svg:path").style("fill",function(d){return h(d.index)}).attr("d",b);q.append("svg:text").each(function(d){d.angle=(d.startAngle+d.endAngle)/2}).attr("dy",".35em").attr("class","selectDisallow").style("font-family","Open Sans, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif;").style("font-size",
"0.6em").attr("text-anchor",function(d){return d.angle>Math.PI?"end":null}).attr("transform",function(d){return"rotate("+(d.angle*180/Math.PI-90)+")translate("+(e+36)+")"+(d.angle>Math.PI?"rotate(180)":"")}).text(function(d){return p(d).gname});var v=i.selectAll("path.chord").data(g.chords()).enter().append("svg:path").attr("class","chord").style("stroke",function(d){return d3.rgb(h(d.target.index)).darker()}).style("fill",function(d){return h(d.target.index)}).style("opacity","0.8").attr("d",d3.svg.chord().radius(e)).on("mouseover",
function(d){if(!d3.select("#gActive").empty()){d3.select(this).transition().duration(250).ease("cubic").style("fill-opacity",1);d3.select("#tooltip").style("visibility","visible").html(f(p(d))).style("top",function(){return d3.event.pageY+50+"px"}).style("left",function(){return d3.event.pageX-130+"px"})}}).on("mousemove",function(){d3.select("#tooltip").style("left",d3.event.pageX+20+"px").style("top",d3.event.pageY+20+"px")}).on("mouseout",function(){d3.select(this).transition().duration(100).ease("cubic").style("fill-opacity",
0.8);d3.select("#tooltip").style("visibility","hidden")})}d3.csv("data/chord-data.csv",function(k,j){var f=chordMpr(j);f.addValuesToMap("isfrom").setFilter(function(a,e,h){return a.isfrom===e.name&&a.goesto===h.name}).setAccessor(function(a){if(!a[0])return 0;return+a[0].count});o(f.getMatrix(),f.getMap())})})()}
function drawMap(){var n=parseInt(d3.select("#mapDiagram").style("width")),m=n*0.7,c=500;(function(){function o(){var g=d3.select(this);d3.selectAll(".countryActive").empty();g.style("opacity","0.8");d3.select("#tooltip").style("visibility","visible").html("<p>"+g.attr("id")+"</p>").style("top",function(){return d3.event.pageY+10+"px"}).style("left",function(){return d3.event.pageX-0+"px"})}function k(){d3.select("#tooltip").style("left",d3.event.pageX+20+"px").style("top",d3.event.pageY+20+"px")}
function j(){var g=d3.select(this);g.classed("countryActive")||d3.select(this).attr("class","countryEU");g.style("opacity","1");d3.select("#tooltip").style("visibility","hidden")}function f(){if(d3.select("#"+this.id).attr("class")==="countryActive"){d3.select(this).attr("class","countryEU");d3.selectAll(".countryEU").transition().duration(c).ease("cubic").style("fill","#217A89");d3.selectAll(".nrCountry").transition().duration(c).ease("cubic").style("opacity",0);d3.select("#selectionTitle").transition().duration(c/
2).ease("quad").style("fill","#FFFFFF").remove();d3.select("#titleCount").transition().duration(c/2).ease("quad").style("fill","#FFFFFF").remove()}else{d3.selectAll(".nrCountry").transition().duration(c).ease("cubic").style("opacity",0).text("");d3.select(".countryActive").attr("class","countryEU");d3.select("#selectionTitle").transition().duration(c/2).ease("quad").style("fill","#FFFFFF").remove();d3.select("#titleCount").transition().delay(c/10).duration(c/2).ease("quad").style("fill","#FFFFFF").remove();
d3.select(this).attr("class","countryActive").transition().duration(c).ease("exp").style("fill","#F47F5E");var g=this.id;console.log(g+" is active");var b=d3.selectAll(".countryEU").data(),i=[],p=0,q;for(q in b)if(b.hasOwnProperty(q)){var v={};v.host=b[q].properties.NAME;v.people=b[q].diaspora[g];i.push(v)}i.sort(function(d,l){return parseFloat(l.people)-parseFloat(d.people)});for(b=0;b<i.length;b++)p+=parseFloat(i[b].people);d3.select("#mapContainer").append("text").attr("id","selectionTitle").attr("x",
10).attr("y",50).style("opacity",0).style("fill","#E7714A").style("text-anchor","left").style("font-size","2.5em").transition().duration(c).ease("quad").style("opacity",1).text(g);d3.select("#mapContainer").append("text").attr("id","titleCount").attr("x",13).attr("y",75).style("text-anchor","left").style("font-size","0.6em").style("font-weight","700").style("fill","#606062").transition().delay(c/2).duration(c*2).ease("quad").style("opacity",0.8).text(d3.format(".2s")(p)+" Expats");g=d3.scale.linear().domain([5,
15,35,60]).range(["#8DA9D3","#3E649D","#3E649D","#3E649D"]);for(b=0;b<i.length;b++){q=(i[b].people/p*100).toFixed(2);d3.selectAll("#"+i[b].host).transition().duration(c).ease("cubic").style("fill",g(q));d3.selectAll("#nr"+i[b].host).transition().duration(c).ease("cubic").style("opacity",1).text(d3.format(".2s")(i[b].people))}}}var a,e,h;h=n*1.3;h=d3.geo.azimuthalEqualArea().scale(h).translate([n/2,n/5]).center([20,58]);e=d3.geo.path().projection(h);a=d3.select("#mapDiagram").append("svg").attr("height",
m).attr("id","mapContainer").attr("width",n).style("display","block").style("margin","auto").append("g");d3.json("./data/map.json",function(g){a.selectAll(".country").data(topojson.feature(g,g.objects.collection).features).enter().append("g").attr("class",function(b){return b.properties.EU_MEMBER==="1"?"gCountryEU":"gCountry"}).attr("id",function(b){return"g"+b.properties.NAME}).append("path").attr("class","country").attr("id",function(b){return b.properties.NAME}).attr("d",e).filter(function(b){if(b.properties.EU_MEMBER===
"1")return b}).attr("class","countryEU").on("mouseover",o).on("mousemove",k).on("mouseout",j).on("click",f);d3.selectAll(".gCountryEU").append("text").attr("class","nrCountry selectDisallow disablePointer").attr("id",function(b){return"nr"+b.properties.NAME}).attr("transform",function(b){return"translate("+e.centroid(b)+")"}).attr("dy",".35em").style("font-weight","bold").style("opacity",0);d3.json("./data/mapdata.json",function(b){for(var i in b)b.hasOwnProperty(i)&&d3.select("#"+i).datum(function(p){p.diaspora=
b[i];return p})})})})()}
function drawJailPop(){function n(){d3.select(this).transition().duration(200).ease("cubic").style("opacity","0.7");d3.select("#tooltip").style("visibility","visible").html("<p>1%</p>").style("top",function(){return d3.event.pageY+10+"px"}).style("left",function(){return d3.event.pageX-0+"px"});d3.select(this.parentNode).datum()}function m(){d3.select("#tooltip").style("left",d3.event.pageX+20+"px").style("top",d3.event.pageY+20+"px")}function c(){d3.select(this).transition().duration(100).delay(100).ease("cubic").style("opacity","1").attr("rx",
0).attr("ry",0);d3.select("#tooltip").style("visibility","hidden")}function o(){var b=d3.select(this),i=b.attr("id").replace(/ /g,""),p=d3.select("#"+i).selectAll("rect").size();b.select("text").text(p+"%").style("font-size","0.9em").style("font-weight","900");d3.select("#jailPopContainer").select("#"+i).attr("class","sqActive");d3.selectAll(".sqInactive").selectAll("rect").transition().duration(200).ease("cubic").style("opacity","0.2")}function k(){var b=d3.select(this),i=b.attr("id");b.select("text").text(i).style("font-size",
"0.7em").style("font-weight","500");d3.selectAll(".sqInactive").selectAll("rect").attr("dx",".35em").transition().duration(400).ease("cubic").style("opacity","1");d3.selectAll(".sqActive").attr("class","sqInactive")}var j=[{Romanian:2},{"Other EU":4},{"Non EU":13},{Local:82}],f=20,a=0,e={top:30,left:0,bottom:20,right:35},h=parseInt(d3.select("#jailPop").style("width"));h=h-e.left-e.right;var g=e.top+e.bottom;(function(){var b=d3.select("#jailPop").append("svg").attr("id","jailPopContainer").attr("width",
h).attr("height",g).style("display","block").style("margin","auto");a=b.attr("width")/100+20;b.append("text").attr("id","jailPopTitle").attr("x",h/2).attr("y",e.top).attr("class","chartTitle").attr("text-anchor","middle").style("fill","#606062").text("EU PRISON TOTAL DOMINATED BY LOCALS (%)");b=b.selectAll("g").data(j).enter().append("g").attr("id",function(l){return String(Object.keys(l)).replace(/ /g,"")}).attr("class","sqInactive");var i=-(a+f),p=0,q=0;b.each(function(l){function r(){i+=a+f;if(i+
a>h){i=0;p++}return i}var t=String(Object.keys(l));l=d3.format("f")(l[t]/1);t=String(t).replace(/ /g,"");for(var s=0;s<l;s++)d3.select("#"+t).append("rect").attr("class","sq"+t+" jailPopSquares").attr("x",r()).attr("y",(q=p*(a+f)+20)+20).attr("rx",0).attr("ry",0).attr("width",a).attr("height",a).on("mouseover",n).on("mousemove",m).on("mouseout",c)});p++;q=p*(a+f)+20;d3.select("#jailPopContainer").attr("height",q+e.top+e.bottom+20);d3.select("#jailPopContainer").append("g").attr("id","jailPopLegend").selectAll("g").data(j).enter().append("g").attr("id",
function(l){return String(Object.keys(l))}).attr("transform",function(l,r){return"translate("+r*(a+f)+","+(q+20)+")"}).on("mouseover",o).on("mouseout",k).append("rect").attr("x",0).attr("y",0).attr("width",a).attr("height",a).attr("class",function(l){return"sq"+String(Object.keys(l)).replace(/ /g,"")});d3.select("#jailPopLegend").selectAll("g").each(function(){d3.select(this).append("text").attr("class",function(l){return"disablePointer selectDisallow sq"+String(Object.keys(l)).replace(/ /g,"")}).attr("x",
a+3).attr("y",a/2).attr("dy",".35em").attr("text-anchor","left").style("fill","#606062").style("font-size","0.7em").text(function(l){return Object.keys(l)})});var v=0,d=0;d3.select("#jailPopLegend").selectAll("g").each(function(){var l=d3.select(this).select("text").node().getBBox().width,r=d3.select(this.nextElementSibling),t=d3.select("#jailPopContainer").node().getBBox().width;if(r[0][0]){var s=d3.transform(r.attr("transform")).translate[0];r=d3.transform(r.attr("transform")).translate[1];s=v+
s+l;if(s+l>t){s=0+d;d=a+f+l;p++;r+=a+f;q=p*(a+f)+20;d3.select("#jailPopContainer").attr("height",q+e.top+e.bottom+20)}v+=l;d3.select(this.nextElementSibling).attr("transform","translate("+s+","+r+")")}})})()};
